apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: downwardapi  # Namespace where the Deployment should be created
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: downward-api-volume
          mountPath: /etc/podinfo  # Mounting the volume to this path
          readOnly: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName  # Setting nodeName as an environment variable
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP  # Setting podIP as an environment variable
      volumes:
      - name: downward-api-volume
        downwardAPI:
          items:
            - path: "pod_name"
              fieldRef:
                fieldPath: metadata.name  # Pod name in a file
            - path: "namespace"
              fieldRef:
                fieldPath: metadata.namespace  # Pod namespace in a file
            - path: "pod_uid"
              fieldRef:
                fieldPath: metadata.uid  # Pod UID in a file
