apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: downwardapi  # Namespace where the Deployment should be created
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: downward-api-volume
          mountPath: /etc/podinfo  # Mounting the Downward API volume to this path
          readOnly: true
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf  # Mount the nginx.conf file from the ConfigMap
          subPath: nginx.conf  # Ensure the file is mounted as nginx.conf
        - name: nginx-config-dir
          mountPath: /etc/nginx/conf.d/  # Mount the conf.d directory for default.conf
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  # Set POD_NAME from the Downward API
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace  # Set POD_NAMESPACE from the Downward API
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid  # Set POD_UID from the Downward API
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName  # Set NODE_NAME from the Downward API
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP  # Set POD_IP from the Downward API
        command:
          - "/bin/sh"
          - "-c"
          - "envsubst < /etc/nginx/nginx.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
      volumes:
      - name: downward-api-volume
        downwardAPI:
          items:
            - path: "pod_name"
              fieldRef:
                fieldPath: metadata.name  # Pod name in a file
            - path: "namespace"
              fieldRef:
                fieldPath: metadata.namespace  # Pod namespace in a file
            - path: "pod_uid"
              fieldRef:
                fieldPath: metadata.uid  # Pod UID in a file
      - name: nginx-config-volume
        configMap:
          name: nginx-config  # Reference the ConfigMap containing the custom nginx.conf
      - name: nginx-config-dir
        emptyDir: {}  # This will hold the final generated config file
