apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: downwardapi  # Namespace where the Deployment should be created
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: downward-api-volume
          mountPath: /etc/podinfo  # Mounting the Downward API volume to this path
          readOnly: true
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx-test.conf
          subPath: nginx-test.conf  # Mount the config file as nginx.conf
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name  # Set POD_NAME from the Downward API
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace  # Set POD_NAMESPACE from the Downward API
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid  # Set POD_UID from the Downward API
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName  # Set NODE_NAME from the Downward API
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP  # Set POD_IP from the Downward API
      volumes:
      - name: downward-api-volume
        downwardAPI:
          items:
            - path: "pod_name"
              fieldRef:
                fieldPath: metadata.name  # Pod name in a file
            - path: "namespace"
              fieldRef:
                fieldPath: metadata.namespace  # Pod namespace in a file
            - path: "pod_uid"
              fieldRef:
                fieldPath: metadata.uid  # Pod UID in a file
      - name: nginx-config-volume
        configMap:
          name: nginx-config  # The ConfigMap with the custom nginx.conf
